apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: asoos-web-monitoring
  namespace: asoos-web-infrastructure
  labels:
    app: asoos-web-infrastructure
spec:
  selector:
    matchLabels:
      app: asoos-auth
  endpoints:
  - port: http
    path: /metrics
    interval: 30s

---
apiVersion: v1
kind: Service
metadata:
  name: asoos-web-metrics
  namespace: asoos-web-infrastructure
  labels:
    app: asoos-web-infrastructure
spec:
  selector:
    app: asoos-auth
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
