version: '3'

vars:
  COMMANDER: "Philip Corey Roark"

tasks:
  v36-health:
    desc: "Victory36 health check"
    cmd: ./ask-victory36.js --health
    
  victory-day:
    desc: "Victory Day celebration"
    cmd: ./ask-victory36.js "Victory Day status report"
      
  dsao-emergency:
    desc: "Emergency Diamond SAO authentication"
    cmd: node emergency-dsao-auth.js
    
  default:
    desc: "Victory36 welcome"
    cmd: echo "Victory36 Task Management - Commander {{.COMMANDER}}"
